### ISSUE TITLE
Any plans to update repo to align with latest Issac Sim version and Replicator YAML migration?

### ISSUE THREAD

**Issue by figkim** [ngzhili/SynTable#1]
Hello,

Based on the content you have worked on, I was able to obtain a custom dataset, including valuable amodal annotations. Thank you for sharing the results.

As you may know, the latest version of Issac Sim has been upgraded to 2023.1.1, and the Replicator Composer used by this repo has been deprecated and migrated to Replicator YAML after that.

I am curious to know whether you intend to update this repo to align with the latest version of Issac Sim. If you have any plans, please let me know!

**Comment by ngzhili** [comment]
We may be updating the Replicator Composer repo to migrate to Replicator YAML. We will update again if we do so
