### ISSUE TITLE
Will the trained model be published?

### ISSUE THREAD

**Issue by gachiemchiep** [ngzhili/SynTable#4]
Hello @ngzhili 
Thank you for your great work. 

Would you mind publish your trained uoais model?

**Comment by HZWang96** [comment]
Hi @gachiemchiep, the trained model should already have been published on Zenodo, along with our dataset. You can download it at this link: [experiment_model_weights.zip](https://zenodo.org/records/10565517/files/experiment_model_weights.zip?download=1)

**Comment by gachiemchiep** [comment]
@HZWang96 
Thank you very much
